# Generated by Django 5.2 on 2025-04-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_statistics_jobs_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='resume_enhanced',
            field=models.IntegerField(default=0),
        ),
    ]
