# Generated by Django 5.2 on 2025-04-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_statistics_resume_enhanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
    ]
