name: Build & Push Docker Image

on:
  push:
    branches: [ main ]  # or your deploy branch
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Optional: Run Django tests
    # - name: Run tests
    #   run: python manage.py test

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/be-skillfolio:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/be-skillfolio:latest
